--------------------------------------------------------
--  文件已创建 - 星期一-十月-06-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "SALIERI"."TEST" 
   (	"ID" NUMBER, 
	"NUM" NUMBER, 
	"QUESTION" VARCHAR2(32 BYTE), 
	"A" VARCHAR2(32 BYTE), 
	"B" VARCHAR2(32 BYTE), 
	"C" VARCHAR2(32 BYTE), 
	"D" VARCHAR2(32 BYTE), 
	"SCORE" NUMBER, 
	"RIGHT" VARCHAR2(32 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "PRACTICE" ;
REM INSERTING into SALIERI.TEST
SET DEFINE OFF;
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (42,42,'1*1','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (43,43,'1*2','1','2','3','4',1,'2');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (44,44,'1*3','1','2','3','4',1,'3');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (45,45,'1*4','1','2','3','4',1,'4');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (46,46,'1*5','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (47,47,'1*6','1','2','3','4',1,'2');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (48,48,'1*7','1','2','3','4',1,'3');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (49,49,'1*8','1','2','3','4',1,'4');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (50,50,'1*9','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (51,51,'2*1','1','2','3','4',1,'2');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (52,52,'2*2','1','2','3','4',1,'3');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (53,53,'2*3','1','2','3','4',1,'4');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (54,54,'2*4','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (55,55,'2*5','1','2','3','4',1,'2');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (56,56,'2*6','1','2','3','4',1,'2');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (57,57,'2*7','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (58,58,'2*9','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (59,59,'3*1','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (60,60,'3*2','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (61,61,'3*3','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (62,62,'3*4','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (63,63,'3*5','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (64,64,'3*6','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (65,65,'3*7','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (66,66,'3*8','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (67,67,'3*9','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (41,41,'1+111','12','45','23','56',50,'112');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (3,3,'1*3','1','2','3','4',1,'3');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (1,1,'1*1','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (2,2,'1*2','1','2','3','4',1,'2');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (4,4,'1*4','1','2','3','4',1,'4');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (5,5,'1*5','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (6,6,'1*6','1','2','3','4',1,'2');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (7,7,'1*7','1','2','3','4',1,'3');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (8,8,'1*8','1','2','3','4',1,'4');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (9,9,'1*9','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (10,10,'2*1','1','2','3','4',1,'2');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (11,11,'2*2','1','2','3','4',1,'3');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (13,13,'2*4','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (14,14,'2*5','1','2','3','4',1,'2');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (15,15,'2*6','1','2','3','4',1,'2');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (16,16,'2*7','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (17,17,'2*9','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (18,18,'3*1','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (19,19,'3*2','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (20,20,'3*3','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (21,21,'3*4','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (22,22,'3*5','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (23,23,'3*6','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (24,24,'3*7','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (25,25,'3*8','1','2','3','4',1,'1');
Insert into SALIERI.TEST (ID,NUM,QUESTION,A,B,C,D,SCORE,RIGHT) values (26,26,'3*9','1','2','3','4',1,'1');
--------------------------------------------------------
--  DDL for Index TEST_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SALIERI"."TEST_UK1" ON "SALIERI"."TEST" ("NUM", "QUESTION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "PRACTICE" ;
--------------------------------------------------------
--  DDL for Index TEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SALIERI"."TEST_PK" ON "SALIERI"."TEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "PRACTICE" ;
--------------------------------------------------------
--  Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "SALIERI"."TEST" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SALIERI"."TEST" MODIFY ("NUM" NOT NULL ENABLE);
 
  ALTER TABLE "SALIERI"."TEST" MODIFY ("QUESTION" NOT NULL ENABLE);
 
  ALTER TABLE "SALIERI"."TEST" MODIFY ("A" NOT NULL ENABLE);
 
  ALTER TABLE "SALIERI"."TEST" MODIFY ("B" NOT NULL ENABLE);
 
  ALTER TABLE "SALIERI"."TEST" MODIFY ("C" NOT NULL ENABLE);
 
  ALTER TABLE "SALIERI"."TEST" MODIFY ("D" NOT NULL ENABLE);
 
  ALTER TABLE "SALIERI"."TEST" MODIFY ("SCORE" NOT NULL ENABLE);
 
  ALTER TABLE "SALIERI"."TEST" ADD CONSTRAINT "TEST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "PRACTICE"  ENABLE;
 
  ALTER TABLE "SALIERI"."TEST" ADD CONSTRAINT "TEST_UK1" UNIQUE ("NUM", "QUESTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "PRACTICE"  ENABLE;
